### ISSUE TITLE
Can not load the file './dmp/data/40x40-smnist.mat'

### ISSUE THREAD

**Issue by linksdl** [shikharbahl/neural-dynamic-policies#3]
Hi, I am doing this project as my final master project, but when I run the command as your guide, the code can not run due to not found a file '40x40-smnist.mat'. Could you help me solve this problem?

**Comment by shikharbahl** [comment]
Hi @linksdl,

Sorry about that we got rid of the dependency in smnist_loader.py: 6c8afe3. However, the array file is too large to share on the repo, so I have provided a downloadable link here: https://drive.google.com/file/d/1oqJBbczrURrGmOU37J3TSCAkwSbqeXzG/view?usp=sharing. Note that you must add the path to this data file in the smnist loader.

**Comment by linksdl** [comment]
@shikharbahl  Thanks for your help very much. I was preparing for my final exam recentely. I will try to run this project.
