### ISSUE TITLE
Is some error in 'smnist_loader.py' file?

### ISSUE THREAD

**Issue by linksdl** [shikharbahl/neural-dynamic-policies#6]
<img width="791" alt="WX20210531-172638@2x" src="https://user-images.githubusercontent.com/12442915/120220964-824be800-c235-11eb-96ae-9bc5fc01ee1f.png">

@shikharbahl  Hi, Could you please confirm 'smnist_loader.py'? 
1, is this a '.mat' file type?
2, 'for image in data[image_key][0,0][0]'?
3, 'DMP_data = data[dmp_params_key][0, 0][0]'?

**Comment by shikharbahl** [comment]
Hi @linksdl,

1) it is a .mat file: https://drive.google.com/file/d/1oqJBbczrURrGmOU37J3TSCAkwSbqeXzG/view?usp=sharing. Note that you must add the path to this data file in the smnist loader.

2 and 3 - this should work with the above file
