### ISSUE TITLE
About the './dmp/data/pretrained_weights.pt' file

### ISSUE THREAD

**Issue by linksdl** [shikharbahl/neural-dynamic-policies#7]
Hi, @shikharbahl, I am struggling with a problem in 'main_il.py'.  Is this parameter  pt='./dmp/data/pretrained_weights.pt your trained model (ndp_cnn) ? If yes, could you upload this file, please?

**Comment by shikharbahl** [comment]
Unfortunately, I lost have acess to the pretrained weights, but the network was trained on MNIST: https://github.com/pytorch/examples/blob/master/mnist/main.py.
